#+title:  functional and efficiency focused computing workflow
#+author: emil lenz
#+email:  emillenz@protonmail.com
#+date:   2023-05-16

#+begin_quote
Tech Geeker: (noun) A programmer nerd who are ignorant of social sciences yet persistently loud of his opinions on many social issues related to programming, such as language popularity, pros and cons of GUI, software engineering practices, software license issues, IT industry practices, ethics of corporations.
--- Xahlee

It may looks ridiculous to the outside observer, but efficiency it’s about eliminating that invisible barrier between you and the tool that you’re using,”
--- Ethan Schonoover
#+end_quote


#+begin_quote
“An idiot admires complexity, a genius admires simplicity, a physicist tries to make it simple, for an idiot anything the more complicated it is the more he will admire it, if you make something so clusterfucked he can't understand it he's gonna think you're a god cause you made it so complicated nobody can understand it. That's how they write journals in Academics, they try to make it so complicated people think you're a genius”
― Terry A. Davis
#+end_quote

* philosophy
- i am of the strong opinion that you should minimize things you do repeatedly.  thus when closing the editor by accident => can be restored instead of redoing everything.  launching emacs on every startup? => just run the daemon in the background => always accessible & no waiting time.
- this config aims at making the workflow the most effective, while being as bare metal and lightweight as possible, avoiding bloat and focusing on speed and amount of computational steps.  (no headaches, no unexpected behavior, minimal mental overhead).
- this system is 100% centered at keyboard usage and provides coherent, consistent and but minimalist navigational commands across the editor (+inbuilt terminal), webbrowser, window manager and other possible applications.  as a base we use vim-bindings in combination with a custom global navigation keybinding-scheme which is used & consistent cross-program.  (bindings should be minimalistic and lightweight, because light goes fast and far)
- using the mouse for non creative, non graphical usages is inefficient and creates mental overhead.  having to take the focus off the project just in order to click some ui takes way more mental capacity and computational steps than neccessary and can be negated by using the keyboard and having the same actions always on the same keys.
- this system is designed to be a workstation.  it is the opposite of a beautiful gui experience that aims to be visually pleasing.
  - no effects (transparency etc), no fancy animations, no window decorations / logos.
  - uses colorcoding whenever possible since this enhances readability.
  - no icons :: fancy visual sugar.  keep it simple, minimalist and extensible (they are only a distraction), instead use colorcoding and font faces for visually separating displayed options.  we care about the functionality of a program, and not what cool logo it has.
  - this system puts emphasis on a text & data driven evironment wherever possible this will reduce complexity and increase extensibility and interchangeablilty.  you will also benefit from a more unified and consistent interface across programs.
- consistency :: this config aims to be globally consistent in its design, behaviour and control.
  - which means things like (colorscheme, font, workflow, keybindings, ui..) were once carefully analyzed, choosen and designed and then implemented as consistent as possible across tools (editor, webbrowser, wm, reader..)
- single focused window :: avoid using splits in your programs and prefer the maximized buffer tabs-only workflow.  (hence we don't include split management bindings in the wm)  i have found it less intrusive and faster to just switch to the tab instead.
  - humans are not designed and not good at multitasking, they excel at linear singular focus processing.
  - splits are mostly useless and take up screenspace, cluttering it with information you are not processing, and that will distract your focus.
  - when you need the buffer/file, it is better to pull it into focus instantly and from muscle memory, instead of letting it occupy your working area.  (it is there when needed instantly but otherwise hidden)
  - enforcing this causes less overhead and more consistency.
  - get rid of the large set of now redundant maps for split management.
- using finders :: completion menus, bookmarks (bindings to hotswitch) and fuzzy finding are exponentially more efficient than navigating and selecting the destinations manually (through something as a gui filemanager)
  - filemanager's have their place only if the file is in proximity / you need an overview.
- ui :: think of the ui as a  hud
  - remove all distractions and think critically if this feature is implemented just because it is possible/showoff/"cool" or because it is a detrimental part of the workflow that enhances the ergongomics/efficiency/possibilities/workflow of the tool.
  - prompts & statusbars on bottom (if neccessary?)
  - completion-menu's / promts are an extensions of the statusbar
    - do not block view
    - consistently on the same spot across all apps (emacs, rofi)
    - they should not distract => use flat mode (dmenu style)
  - use thin/lightweight/sharp over thick/heavy/rounded (box drawings / terminal characters / symbols)
    - 1px lines, borders with hard corners & sharp edges have their own beautiful, highly functional aestetic.
    - thin and sharp will create less obstruction (having more complex and voluminous symbols/ui than actually neccessary for visual distinction is bloat and visual sugar)
    - minimal and thin feels more soulless and is more ergonomic with screenspace
  - prompts :: using ~>~ globally (shell, rofi,..) for prompt indicator symbol
- thinking fast & slow :: rely on fast, instinctive thinking for non repeating tasks and for repeating patterns / actions on the slow, precise, analytical thinking.
  - this is the definition of dry, or not repeating yourself / taking the minimal required no.  of actions to get to the disired output/position.
  - ex: use vims search replace with patterns instead of manually going through and changing each instance
  - ex: relative line jumping over spamming =j=
  - ex: tab switching => thinking fast & instinctive, develop muscle memory (when there are too many => use analytical brain by searching through the list)
- its all about preserving the working state between sessions to achieve consistency and minimize time needed to get working.  this is why we run emacs as a background daemon.  why we don't poweroff a computer and instead just hibernate/sleep it.

** The mouse
#+begin_quote
My preference for emacs boils down to the fact that it doesn't force me to use a mouse.  A mouse is a pseudoanalog device that suffers from all the control-theory anomalies like overshoot and oscillation, plus lack of haptic confirmation.  Using the mouse forces my hands off the home row, forces my eyes off my cursor (to the target of a gesture).  The mouse and all its control-theory ephemera are a source of sheer agony.  They cause me to hate my computer and to tire quickly from any use of it.  Emacs, however, lets me focus my mind, keep my hands in an efficient pose, lets me look at my work, gives me digital feedback (press a physical keyboard button, see a result, no overshoot and oscillation) and enables longer hours in a state of pleasant flow.

It's not Emacs specifically, but any computer tool that helps me avoid mousing.  Along with mousing goes all those proprietary binary formats for documents: anything but ASCII (or, begrudgingly, UTF-8) must be banned.  Long-live Emacs, org-mode, org-table, org-babel, LaTeX, git, and everything that can be represented in plain text.

There is a special ring in Dante's inferno for the inventor of the mouse and for the legions of GUI designers that built all the World's software around it.
--- anonymous
#+end_quote

* modus-theme
[[https://protesilaos.com/emacs/modus-themes][modus-themes info]]
[[https://protesilaos.com/codelog/2023-01-06-re-modus-questions-disability/][modus-themes legibility theory]]
the purpose of a theme is to optimise the presentation of any given interface.
i find that light themes are superior to dark themes.   studies & research have found the following advantages of using a light-theme over a dark-theme ::
- significantly better proofreading (catch more errors in code, misread less)
- high legibility at low brightness / in direct sunlight => less eyestrain, more efficient battery usage
- no astigmatism (bloom of the letter's which causes them to appear blurry & strains the eyes)
for modus themes, #ffffff and #000000 as the base are minimalist colors are the least limiting on the range of different colors that can be use while maintaining stark contrast.
you should never use the computer with no ambient light sources in the room anyways (for concentration) but the display brightness must be adjusted align with the ambient brightness.   thus in dim light (night), an additional source of light other than that of the monitor are required to reduce eye strain.   the eyes are more relaxed (strain less) when they do not have to focus on one point to gather light.  light theme legibility during day is vastly better than dark theme.
one may object that dark themes "look cooler", which we can ignore, since we use our computer's as a productive tool and not to impress anyone over the internet.

* font: iosevka comfy
 it is incredibly compact in width to allow a lot of code on screen, especially when viewing content side by side. designed for writing code, using in terminals, and preparing technical documents.
  - the intent is to make everything feel part of the same aesthetic, hence setting the font system-wide.
 it was specifically designed for long editor sessions (8- hours).  it aims to reduce eye strain and help readability in the long term.  (try a light theme with a bitmap font like terminus for 8 hours.  it will be a tormenting experience! to maximamise the difficulty, do it in a dark room with the monitor’s brightness set to its maximum value.)
 keep the fontsize as small as you can manage while the font is not blurry (for 1920x1080 that corresponds to size: 10).
  - working with big fontsizes, encourages bad eyesight and neckposture.
  - makes you faster
  - less disorientatation in the buffers
  - less context switching
 it is lean, thin and sharp.  this allows it to be used in all context and interfaces.
 economical use of screen space and clarity/legibility at small sizes.
#+begin_quote
Iosevka Comfy optimises for inter-glyph and inter-style consistency within the overarching constraint of usability at small point sizes.  The shapes are round and are designed in concert to both impose a predictable rhythm and keep characters distinct from each other.  Distinctions are drawn on the premise of contributing to the demands of the design in light of usability, without ever calling attention to themselves (as opposed to sporadic calligraphic glyphs amid an otherwise austere presentation which seem to say "look how pretty I am!").
 --- protesilaos stavrou
#+end_quote

* dependencies
- all packages & other commands found under: [[file:setup_fedora.org][setup script]]

* software
the aim is to be able to run software for years without it breaking or bugging.
learning a tool is an investment and you wouldn't want to sink your time into soemthing that will be useless in a short time.
this is why secure and fast languages such as rust and go are preferred over inconsistent and hacky languages such as perl or python, that require constant maintaining.
i'm very opinionated and have high standards regarding design process and the philosophy behind the tools focused on, hence the selection undergoes a rigorous coparison and selection process.
we favor cli shells, and ~dmenu-scripts~ over GUI applications (eg. using bluetoothctl to setup/manage bluetooth devices and ~bluetooth-menu~ to connect to them after once setup.)

** webbrowser: firefox
*** install & configure extensions manually
- password manager
- theming (light)
- font set all font choices to the system wide font: iosevka comfy 10 and set: don't allow webpages to custom fonts.  that way it will always look uniform.

*** useage
- pin tabs that you want to assign to fixed hotkeys ([[kbd:][M-<number>]]), such as [[https://chatgpt.com]] or [[https://spotify.com]].  they will automatically open and you cant't accidentally close them with [[kbd:][C-w]].
- bookmarks: name them hierarchically w keywords (syntax like ~org-mode-tags~), ex: ~cs:math:exercises~
  - quickly open website using bookmark searching
  - structured, easy to patternmatch (not having to put them into folders)
- use ~*^%~ in the searchbar for finding tabs, bookmarks & history
- make use of google search operators (~site:~, quoting, ~-~)
- use inbuilt shortcuts...

* scripting: using ruby
we never script using the POSIX-shell.  the shell is only meant to be used to run simple shell commands.  if we need to do more than that (eg. programming constructs such as loops, functions, variables, using ~sed/awk/cut...~) then we simply switch over to using the proper scripting language ~ruby~ (alternatively ~python~ if the script must be portable).

shell is coherent with respect to the mind of certain benevolent dictator.  shell is a steaming pile of inconsistent user-unfrienly shit.

on the command line, i don't really need a full language with a repl-like interface.  i want a fast and quick way to interface with the os.  anything beyond that should be written in a proper language (~ruby~) that will inherently bring more benefits.

- long-flags :: when writing shell commands in scripts one should always favor ~--long-flags~ over ~-l~ in order to increase code readability  and maintaineability.  this makes understanding the script for people who may not be familiar with the programs easier to understand and modify (reduce elitism in free software).

*** ruby scripting rationale
a shell only exists for interactive use and running commands: launching processes/commands, interaction with the filesystem and programs (mv, cp, find, grep..).
for scripting however, anything that cannot be done in a oneliner (using && || etc.).  for example: data manipulation (JSON, etc.), conditional execution (if else), functions or the usage of variables/datastructures, you should always opt towards a proper scripting language such as ruby.  since it offer's full library support, is more extensible and maintaineable.

even though it may have a steeper learning curve and requires a more structured and less hacky approach to scripting.  but once fluent in it, it smoothly bridges the gap between compiled highly efficient languages such as rust or c and the interactive nature of a shell.

choosen over python since it is well designed, has a very minimal, clean, consistent syntax.  close interconnectedness with ~sh~ by running ~sh~-commands with ~``~.  i love the fact that everything is a expression (has a value).  This means, it's a extreme joy for functional programers.  Python is pretty badly designed, lots inconsistencies in syntax as well as semantics.  ruby follows the MIT philosophy of making the userinterface consistent and a joy to use.

* keybindings
- typing technique :: get into the habit of proper technique in touch typing.  staying on the homerow, typing with little pressure as needed and not using excess force.  this includes touchtyping all numberrow symbols, brackets & braces.  to enforce this, spraypaint the keycaps blank in order to force you to never look at the keyboard again.  force yourself to use the right finger for the right key (right side symbols :: all with the pinky)
- key-repetition :: disabled.  it empowers bad habits of you holding down a key instead of moving intelligently and fast using the appropriate motion (not holding down [[kbd:][j, k]] instead using [[kbd:][C-u/d]]  not spamming delete, instead using [[kbd:][d-motion]]
- remaps :: [[file:config/.config/xremap/config.org][remapping tool (xremap) configuration file]]

***  workflow
when you need to navigate to a different file/tab, this should be your order of modus-operandi ::
1. alternate buffer [[kbd:][C-<tab>]] :: when you are alternating between 2 files/tabs or need to just goto back to the last visited buffer.  this takes the least amount of overhead and is the fastest.
2. goto tab [[kbd:][M-<number>]] :: assign a tab/file to each number (pinned tabs in browsers, ~harpoon~ in emacs) you can then navigate between these files/tabs instantly without mental overhead.  we are intentionally restricted to a max of 4 tabs.  we want to ensure that it really is frequently visited files and keep the overhead of remembering which file/tab is on which number so low that we can always subconciously jump between the files/tabs.
3. find buffer/tab :: search through the list of open buffers/tabs to switch to the one you need.

* principles
** keep your workflow dry
when you find yourself doing the same things repetitively or you get annoyed it is time to find a program / plugin / script for that step to facilitate the workflow.  (if there is none => write your own script (eg.  killprocess script).

** review the worflow
- review the tool's and workflow you are using from time to time (see if you're missing out and can use something better).
- disable parts of the configuration and evaluate wether it is neccessary or has become obsolete/bloat.

** save state & progress
- ex: do not shut down the computer.  instead: hibernate // shuts it down, but preserves the working state & restores it => resume where left off

** the mit-approach
- simplicity :: the design must be simple, both in implementation and interface.  it is more important for the interface to be simple than the implementation.
- correctness :: the design must be correct in all observable aspects.  incorrectness is simply not allowed.
- consistency :: the design must be consistent.  a design is allowed to be slightly less simple and less complete to avoid inconsistency.  consistency is as important as correctness.
- completeness :: the design must cover as many important situations as is practical.  all reasonably expected cases must be covered.  simplicity is not allowed to overly reduce completeness.

#+begin_quote
When i write software, i write and think of it mostly in the timespan of decades, not shortterm.  Hence valuing languages like C, which will still compile, even in a decade from now.
--- alexey kutepov (tsoding)
#+end_quote
This same principle is applied to plain text computing.
