#+title:  fedora system install
#+author: emil lenz
#+email:  emillenz@protonmail.com
#+date:   2024-12-01
#+info:   moved from arch -> fedora on: 2023-05-28
#+property:  header-args:sh :tangle yes :shebang #!/bin/bash

* info
- if you use a different distro you ensure to install at least these packages for the system config to be able to work. (no guarantees...)
- run this script with sudo! (for ~dnf~)

* setup
#+begin_src sh
git clone --depth=1 https://github.com/emillenz/config ~/Dotfiles
#+end_src

alias
#+begin_src sh
alias dnf="dnf --assumeyes"
#+end_src

- update all packages before doing anything
#+begin_src sh
dnf upgrade
#+end_src

* link neccessary config files
- we use GNU stow and symlink the important config files to keep them all centralized in the same directory and symlink them to the respective places.
- backup your own config directory if neccessary since this will override any previous configuration.
#+begin_src sh
dnf install git stow
cd ~/Dotfiles
stow --adopt home config bin

# override all existing files if you had existing configs
git revert .
#+end_src

* systemwide font
- @readme
#+begin_src sh
git clone --depth 1 https://github.com/protesilaos/iosevka-comfy $HOME/.local/share/fonts
#+end_src

* shell: zsh
- we use emacs's ~comint-mode~ for shell-prompts, so we don't have to configure the shell much.  but zsh is more sane than bash, for the rare time we do still need a regular terminal.
#+begin_src sh
dnf install zsh
sudo chsh --shell /bin/zsh
chsh --shell /usr/bin/zsh
#+end_src

* terminal & tools
- fd + rg :: better defaults than ~find, grep~.  utilized in emacs.
- tldr :: cheatsheet style documentation
- terminal :: emacs.  (for CLI's, use any terminal, doesn't matter)
- rest :: dependecies for emacs/terminal tools
#+begin_src sh
dnf install alacritty fd-find ripgrep tldr curl
#+end_src

* scripting & menu-scripts: ruby
#+begin_src sh
dnf install ruby ruby-devel irb
gem install solargraph rubocop
#+end_src

* make system-scripts executeable
#+begin_src sh
find ~/Dotfiles/bin/.local/bin -type f -exec chmod +x {}\;
#+end_src

* never sudo-password-prompt
#+begin_src sh
echo "$USER ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee "/etc/sudoers.d/$USER"
#+end_src

* editor: doom emacs
#+begin_src sh
dnf install emacs-gtk+x11

# HACK :: supress pure emacs-gtk warning (fedora problem)
sudo alternatives --set emacs /usr/bin/emacs-gtk+x11

git clone --depth 1 https://github.com/doomemacs/doomemacs $HOME/.config/emacs
$HOME/.config/emacs/bin/doom install
#+end_src

- formatter
#+begin_src sh
sudo dnf install npm
npm -g install prettier
#+end_src


* keybindings
- [[https://github.com/xremap/xremap][xremap]]
- configure it to run without ~sudo~ (works after reboot)
#+begin_src sh
dnf copr enable blakegardner/xremap
dnf install xremap-x11 # fedora i3 needs x11, normal xremap don't work

# Make sure uinput is loaded
/sbin/lsmod | grep uinput || echo uinput | sudo tee /etc/modules-load.d/uinput.conf

# Add your user to the input group and add udev rule
sudo gpasswd -a $(whoami) input
echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/input.rules
#+end_src

* wm workflow packages
- i3 :: wm
- mpv :: minimalist video player
- feh :: image viewer
- arandr :: output configurations
- unclutter :: hide mouse cursor after inactivity  @autostart script
- firefox :: browser
- playerctl :: used to control media via keybindings
- bluetoothctl :: setup/manage bluetooth devices
- dunst :: desktop notifications
- feh :: images
- xset :: keyboard settings (repeat off, etc.) @autostart script
- xsetroot :: set wm background to fixed color (=modus-operandi-bg=)
- pamixer :: configure audio
- keepassxc :: passwordmanager.  install browser extension + configure it's settings: run on startup, minimize to systray, don't kill on close.
- scrot :: screenshots (via keybindings).
- zathura :: minmalist pdf viewer (with vim-bindings )
#+begin_src sh
dnf install i3 xdg-utils arandr mpv brightnessctl unclutter firefox playerctl bluetoothctl dunst feh maim xset xsetroot keepassxc scrot

dnf install zathura zathura-pdf-mupdf

# dependency for fedorea preinstalled volume control
dnf install mesa-libEGL-devel

# create screenshot directory
mkdir --verbose --parents ~/Pictures/screenshots
#+end_src

* batsignal
- battery notifications (since we have statusbar turned off) @autostart script
#+begin_src sh
# dependency
dnf install libnotify-devel

git clone --depth=1 https://github.com/electrickite/batsignal && cd batsignal
make
sudo make install
#+end_src

* sshd: for github, sycnthing...
#+begin_src sh
sudo systemctl enable sshd
#+end_src

* sync tools
- syncthing :: for keeping filesystem in sync across multiple machines (daily usage).  started manually when sync is required.
- restic :: backup the userfiles (redundency for when harddrive is destroyed / newinstall required / accidental ~rm~).  manually backed up to an external HDD weekly.
#+begin_src sh
dnf install syncthing restic
#+end_src

- timeshift :: backup & restore system configuration (when system breaks)
- anacron :: run ~timeshift~ daily
#+Begin_src sh
dnf install timeshift
echo '1 0 system-backup sudo timeshift --create' | sudo tee --append /etc/anacrontab
#+end_src

* c/cpp
#+begin_src sh
dnf install cmake gcc clang clang-tools-extra
#+end_src
