#!/usr/bin/env sh

# ---
# title:  stow script
# author: emil lenz
# email:  emillenz@protonmail.com
# date:   [2025-03-28]
# ---

alias stow="stow --restow --ignore='^.git$'"
stow config --target "$HOME/.config"
stow home --target "$HOME"
stow emacs --target "$HOME/.emacs.d"
stow X11 --target "/etc/X11/xorg.conf.d/"
