#+title:  xremap keyboard remapping config
#+author: emil lenz
#+email:  emillenz@protonmail.com
#+date:   2024-01-18
#+property: header-args:yaml :tangle config.yml

* info
 - gtk :: gtk apps are configured to use readline bindings already (gtk-emacs-keytheme) if you are on a different linux machine, use gnome-tweak-tools and: ~setxkbmap -option ctrl:nocaps~.  you use [[kbd:][C-[]] instead of [[kbd:][esc]].  for windows use ~power-toys~ same effect.
 - we want to reduce the depth of layering in our system.  layers always bring an increase in complexity and introduce mental overhead which is our aim to reduce as much as possible without limiting functionality.
 - no homerowmods / layers :: they greatly increase the complexity of the keybinding layer's and introduce unneccessary mental overhead.  additionally and most importantly they cause a delay in typing the actual character which is absolutely inacceptable.  (slow's you down, bottlenecking your typing speed)
 - no vim layer :: we purposefully do not implement a vim-navigation layer globally, since if you are doing more than just typing something into a prompt, you should just use ~emacs-everywhere~ instead.
 - [[kbd:][ctrl, esc]] :: mapped to [[kbd:][capslock]].  this greatly increases ergonomics and speed for all ctrl-bindings.
   - when bill-joy orignially developed VI, the terminal's keyboard, had [[kbd:][esc]] on todays [[kbd:][tab]] and [[kbd:][ctrl]] on [[kbd:][caps]]  this is where [[kbd:][ctrl]] should have always stayed at.
 - deleting characters :: instead of spamming unergonomic [[kbd:][backspace]], get in the habit of always directly using [[kbd:][C-h/w/u]] instead.  these bindings are implemented for all gtk apps using the gtk-emacs-keytheme.
 - browser :: use same keybindings [[kbd:][C-n/p]] as in emacs/dmenu to navigate completion (suggested urls,...)
 - primitive alternative :: ~setxkbmap -option ctrl:ralt_rctrl~

#+begin_src yaml
modmap:
  - name: global
    remap:
      capslock:
        held: ctrl_l
        alone: esc
        one_timeout_milis: 100

keymap:
  - name: browser
    application:
      only: firefox
    remap:
      C-n: down # vim :: navigate completion candidates (suggested urls...)
      C-p: up
#+end_src
