#+title:  i3 literate configuration file
#+author: emil lenz
#+email:  emillenz@protonmail.com
#+date:   [2023-05-15] <- ([2024-11-15] version: marks & literate style)
#+property: header-args:conf :tangle config :noweb yes :comments link

* [ ] revise structure
put media bindings after leader
* [ ] separate XF86 & mouse bindings into sep. blocks
* [ ] add: no notifications (for minimalism, no distractions)

* preface
- [[https://i3wm.org/docs/userguide.html][i3 user-guide]]
- doing changes in system (eg. volume change / internet connection change) are displayed via :otifications.  so we don't need the statusbar (only for leadermode indication) for a more focused workflow and more/clean screenspace.
- i3 exhibits the usual elitism amongst minimal window managers: don’t be bloated, don’t be fancy (simple borders are the most decoration it has).  do not add further complexity when it can be avoided.
- manual tiling wm ::  which superior to an autotiling wm, (or god forbid a desktop-environment), since we always use all windows maximized.
- the windowmanager follows the philosopy of eliminating mental overhead and the neccessity to arrange windows or layouts.
  - eliminate mental overhead and reduce computational steps to get to where you need to be.
  - finetuned to automate the workflow as much as possible. (autostarting all frequently used programs, pinning frequently used browser tabs to [[kbd:][M-<num>]])
- accessing a program is as efficient as possible and always consistent, no matter where in your desktop you are (different monitor/workspace/app order) you will not alt+tab through apps to get to the one you are thinking of.  instead the program is assigned a mark which you can goto to always using the same consisten mnemonic keybinding.
  - we do not use a per-program workspace workflow.  introduces layers of complexity as you need to remember the workspace for pop-up windows & programs.  managing and navigating the workspaces is disorienting and complex.
  - we essentially extend our emacs/vim workflow of using harpoon to jump between files onto the wm, using global marks to goto to buffers immediately.  the only improvement is that we always preassign certain marks for our frequently used programs (editor, webbrowser, terminal, ...).
- keyboard driven workflow only => vi-mnemonic bindings.  has a leader key system inbuilt that allows a extensible modal keybindingsystem.
- strictly avoid multitasking => always work in maximized-mode to never have to resize a window => one workspace per window, to not get distracted by other open windows.
- if at work and forced to use a desktop environment, just use [[kbd:][M-<tab>]] to switch windows and resize your emacs/webbrowser in a similar fashion to get 90% of the benefits of i3.
- we use i3's leadermode in combination with ~dmenu~ to extend our efficient, extensible and fast emacs workflow of using global keybindings in leadermode and minibuffer prompts for interactive commands & input.  dmenu is visually and functionally similar to emacs minibuffer (also in flat mode, same keybindings).
- implement only high-usage-frequency top-level bindigs as the user might be an emacs user, hence using [[kbd:][Meta]].  otherwise ~<leader>~ is used (for infrequent bindings).

** single monitor only
:PROPERTIES:
:created: [2024-05-21 Tue 11:38]
:END:
- we don't have/use multiple monitors.  instead just get used to the efficient & fast navigation- to navigate within virtual workspaces (using a window manager) which is faster (than physically reorienting your FOV) more extensible (have as many as you need), and more consistent (always available, even when on laptop).
- this is consistent with the navigational workflow inside emacs, where we also never use splits and instead use the current window.
- managing windows over multiple monitors becomes increasingly complex and produces overhead.  it's faster to switch to the window you need instantaneously with a keyboard shortcut, instead of physically tilting the head (which is also unergonomic).  additionally we want consistency in the workflow inbetween using the laptop and desktop setup (if you even have that).
- using a single monitor only not only makes you faster, but it also aligns with the focused singletasking fullscreen workflow.
- hence we don't include any bindings to move workspaces/windows between outputs.

* macros
- no statusbar => using notifications to display volume change
#+begin_src conf
set $MV move container to workspace
set $SHCMD exec --no-startup-id
set $ESC mode "default"
set $START_SHCMD exec_always --no-startup-id
set $DMENU_THEME -b -i -fn 'Comic Code-9' -nb '#ffffff' -nf '#000000' -sb '#c0deff' -sf '#000000'

set $VOL_INC pamixer --unmute --increase 5 && dunstify --replace 69 "vol: $(pamixer --get-volume-human)"
set $VOL_DEC pamixer --unmute --decrease 5 && dunstify --replace 69 "vol: $(pamixer --get-volume-human)"
set $VOL_MUTE pamixer --toggle-mute && dunstify --replace 69 "vol: $(pamixer --get-volume-human)"
set $MIC_MUTE pamixer --default-source --toggle-mute && dunstify --replace 69 "mic-mute: $(pamixer --default-source --get-mute)"
set $PLAYERCTL_PLAY_PAUSE playerctl play-pause && dunstify --replace 69 "$(sleep 0.1 && playerctl status)"

set $SYS_SLEEP i3lock --color ffffff && systemctl suspend
#+end_src

* start processes
- ensure these programs/daemon's are always running

#+begin_src conf
$START_SHCMD emacsclient --reuse-frame || (emacs --daemon && emacsclient --create-frame)
$START_SHCMD pgrep firefox || firefox
$START_SHCMD pgrep playerctld || playerctld
$START_SHCMD pgrep unclutter || unclutter
$START_SHCMD pgrep batsignal || batsignal -bpe -w 50 -c 20 -d 5
$START_SHCMD pgrep nm-applet || nm-applet
$START_SHCMD pgrep keepassxc || keepassxc
#+end_src

- background :: minimalist modus-vivendi bg color
#+begin_src conf
$START_SHCMD xsetroot -solid '#ffffff'
#+end_src

no auto screensaving/powersaving (annoying when studying).  when we want the screen off, we do it manually.
#+begin_src conf
$START_SHCMD xset dpms 0 0 0
$START_SHCMD xset s off
#+end_src

keyremaps + disable key repeat (efficiency!)
#+begin_src conf
$START_SHCMD pgrep xremap || xremap --watch=device ~/.config/xremap/config.yml
$START_SHCMD xset r off
#+end_src

* opts
- minimalist (to none) border
- force all windows into tabbed mode, never allow floating windows.
- no widow icons (bloat)
#+begin_src conf
workspace_auto_back_and_forth no
workspace_layout tabbed
force_focus_wrapping no
default_orientation horizontal
# <pixel> hides titlebars when it's the only window on the workspace
default_border none
default_floating_border pixel 1
title_align left
font pango: Comic Code 10
focus_on_window_activation focus
smart_gaps inverse_outer
#+end_src

* keybindings
- MOD = [[kbd:][alt]] :: this is ergnomic for laptops and custom keyboards alike.  we otherwise don't need [[kbd:][alt]], since we only use [[kbd:][ctrl]] within applications (and don't use emacs keys).
- disable mousewheel functionality :: no accidental window switching wheen mouse is still on titlebar
- accessibility :: we map XF86 keys for large keyboards & laptops, but most functions also available without taking the hands off the keyboards (or if minimalist keyboard without XFkeys)

#+begin_src conf
set $MOD Mod1
floating_modifier $MOD
# we don't tile
tiling_drag off
bindsym button2 kill
bindsym --whole-window $MOD+button2 floating toggle
bindsym button4 nop
bindsym button5 nop

bindsym XF86MonBrightnessDown $SHCMD brightnessctl set 5%-
bindsym XF86MonBrightnessUp $SHCMD brightnessctl set 5%+
# to reset screenlayouts when disconnecting laptop from external output
bindsym XF86Display $SHCMD xrandr --auto
bindsym XF86Sleep $SHCMD $SYS_SLEEP
bindsym XF86AudioPlay $SHCMD $PLAYERCTL_PLAY_PAUSE
bindsym XF86AudioPause $SHCMD $PLAYERCTL_PLAY_PAUSE
bindsym XF86AudioNext $SHCMD playerctl next
bindsym XF86AudioPrev $SHCMD playerctl previous
bindsym XF86AudioLowerVolume $SHCMD $VOL_DEC
bindsym XF86AudioRaiseVolume $SHCMD $VOL_INC
bindsym XF86AudioMute $SHCMD $VOL_MUTE
bindsym XF86AudioMicMute $SHCMD $MIC_MUTE

bindsym $MOD+minus $SHCMD $VOL_DEC
bindsym $MOD+equal $SHCMD $VOL_INC
bindsym $MOD+bracketright $SHCMD playerctl next
bindsym $MOD+bracketleft $SHCMD playerctl previous
bindsym $MOD+backslash $SHCMD $PLAYERCTL_PLAY_PAUSE
#+end_src

* navigational bindings
provide minimal navigational bindings, all you need for the workflow.
- dmenu :: you can pass flags/args to programs as neccessary (eg. ~emacs -Q~)
- use the application native quit shortcut (shell: [[kbd:][C_d]], [[kbd:][C-q/C-w]] in GTK-apps).  allow the process to exit as intended (eg. caching data for next time.  eg:shell: requiring confirmation if jobs are still running).  only use ~kill~ & ~kill-process-menu~ as a last resort.
#+begin_src conf
bindsym $MOD+p focus left
bindsym $MOD+n focus right
bindsym $MOD+q kill
bindsym $MOD+Tab workspace back_and_forth

bindsym $MOD+Return $SHCMD i3-dmenu-desktop --dmenu="dmenu -p 'desktop-run >' $DMENU_THEME"
bindsym $MOD+shift+Return $SHCMD dmenu_run -p 'run > ' $DMENU_THEME
#+end_src

* gaps
we only ever use a single window (no splits) in our editor/terminal, thus for text-based programs (editor/terminal...) ::
- constrain window-width and center windows to the middle of the screen.  whereas normally they are offset to the left edge of the screen.  whereas other windows contents (like the browser) are already ergonomically centered and constrained, which causes you to refocus the fov from the edge to the center of the window (& vice versa).
- this makes our single-focus workflow more ergonomic and focused.
- no long lines ::
  - improved readability & focus of textparagraphs, especially if you stare at the computer for 8+ hours a day.
  - the displayed data is more compact and coherent
  - reading code/data/formulas, and vertical vim navigation, is easier top to bottom vs horizontally.
    - take math as example, its easier to read equations if they are short, concise and aligned on a newline, rather than in one long equation.
    - coding: typically one (short) statement per line.
- line wrap :: command outputs or browser webpages are often not fixed to some width, instead displayed across the entire available width, thus making it very hard to not loose focus of the current line.  using gaps, it makes the text easier to read.
- no manual adjustment :: you should never manually resize gaps, find an optimal setting for your setup (hence the lack of bindings).  in special cases you may toggle fullscreen to get rid of gaps.
- gaps :: depend on screen resolution.  optimized for editor (100pts fill margin) and termina output.
- toggle gaps for special casses :: somtimes you have a unformatted website, toggle gaps on.  sometimes you have special output in terminal that requires fullscreen etc...

#+begin_src conf
set $GAPSIZE 500
bindsym $MOD+z gaps horizontal current toggle $GAPSIZE
#+end_src

* workspaces
- the idea is to bind to the abstract function of the program, and not to the specific instance itself => if a different program is used, the functionality and bindings remain the same.  (eg: vim instead of emacs).
- if you are forced to work with a desktop environment, you can easily replicate this config by manually putting clients on separate workspaces and using [[kbd:][MOD+<number>]] to switch.
- workspace assigned programs are started automatically by the ~autostart~ script and a binding to open them client-server style when it makes sense (if accidentally closed), all other apps are to be opened via dmenu desktop laucher.  ensuring these programs are always running just reduces mental overhead and startup time.
- the parenthesis around the commands are required, otherwise undefined behaviour.
- we use per program workspaces and not just jumping to a specific program, since this alings more with the full focus workflow.  when we are working on something, we want to focus in on it, not multitask between mutiple different windows.
- workspaces allow multiple windows of the same class to be opened on the same workspace (eg. multiple instances of zathura).
- get window title & class information using: ~xprop~
- for windows that are not assigned to workspaces it is most efficient to use the dmenu ~window-menu~.

#+name: workspaces
#+begin_src elisp
(require 'dash)

(mapconcat #'identity
	   (->> '(("all" ".")
		  ("edit" "Emacs"
		   "emacsclient --reuse-frame || (emacs --daemon && emacsclient --create-frame)"
		   t)
		  ("read" "Zathura")
		  ("term" "Alacritty" "alacritty" t)
		  ("web" "firefox" "firefox"))

		(-map (lambda (tuple)
			(-let* (((name class cmd gaps?) tuple)
				(key (substring name 0 1)))
			  (mapconcat #'identity
				     (remove nil
					     (list (format "for_window [class=\"%s\"] move container to workspace %s" class name)
						   (format "bindsym $MOD+%s workspace %s" key name)
						   (when cmd (format "bindsym $MOD+shift+%s $SHCMD %s" key cmd))
						   (when gaps? (format "workspace %s gaps horizontal $GAPSIZE" name))))
				     "\n")))))
	   "\n")
#+end_src

#+RESULTS: workspaces
#+begin_example
for_window [class="."] move container to workspace all
bindsym $MOD+a workspace all
for_window [class="Emacs"] move container to workspace edit
bindsym $MOD+e workspace edit
bindsym $MOD+shift+e $SHCMD emacsclient --reuse-frame || (emacs --daemon && emacsclient --create-frame)
workspace edit gaps horizontal $GAPSIZE
for_window [class="Zathura"] move container to workspace read
bindsym $MOD+r workspace read
for_window [class="Alacritty"] move container to workspace term
bindsym $MOD+t workspace term
bindsym $MOD+shift+t $SHCMD alacritty
workspace term gaps horizontal $GAPSIZE
for_window [class="firefox"] move container to workspace web
bindsym $MOD+w workspace web
bindsym $MOD+shift+w $SHCMD firefox
#+end_example

(read: ~M-x info-display-manual org~ chapter: =16 working with source code=, if you don't know what this magic is doing)
#+begin_src conf
<<workspaces()>>
#+end_src

- HACK :: must come after specific workspaces (applies to all windows).
#+begin_src conf
for_window [all] focus, title_window_icon no
#+end_src

* leader
- bind infrequently used commands and menus
#+begin_src conf
bindsym $MOD+space mode "leader"

mode "leader" {
	bindsym $MOD+a $ESC; $SHCMD audio-output-menu $DMENU_THEME
	bindsym $MOD+b $ESC; $SHCMD bluetooth-menu $DMENU_THEME
	bindsym $MOD+k $ESC; $SHCMD kill-menu $DMENU_THEME

	# screenshot
	bindsym $MOD+s $ESC; $SHCMD scrot --select --file "$HOME/Pictures/screenshots/%Y-%m-%d_T%H-%M-%S.png" --exec 'dunstify "screenshot" "$f"'

	bindsym $MOD+e $ESC; $SHCMD emacsclient --eval "(emacs-everywhere)"
	bindsym $MOD+q $ESC; $SHCMD $SYS_SLEEP
	bindsym $MOD+o $ESC; move workspace to output next
	bindsym $MOD+m $ESC; $SHCMD $VOL_MUTE
	bindsym $MOD+shift+m $ESC; $SHCMD $MIC_MUTE

	bindsym Escape $ESC
}
#+end_src

* modus-operandi theme
#+begin_src conf
set $BG          #ffffff
set $FG          #000000
set $MODELINE_BG #c8c8c8
set $BORDER      #9f9f9f
set $ACTIVE_BG   #c0deff
set $URGENT_BG   #ff8f88

## element              $border    $bg          $fg $mark $border (child)
client.focused          $ACTIVE_BG $ACTIVE_BG   $FG $FG   $ACTIVE_BG
client.focused_inactive $BORDER    $MODELINE_BG $FG $FG   $BORDER
client.unfocused        $BORDER    $MODELINE_BG $FG $FG   $BORDER
client.urgent           $URGENT_BG $URGENT_BG   $FG $FG   $URGENT_BG
client.background       $BG
#+end_src

* modeline
** modeline / tabbar
- a wm statusbar unneccessarily take up screen real-estate and usually just causes a distraction rather than actually being useful.
  - you don't need visual indication of how to navigate to tabs, each specific tab is always on the same keybind, and if not it's faster to search for it than visually navigate/select some list / menu.
- for full immersion, reduced distraction and enhanced focus, disable it and work fullscreen.
  - no overlapping functionality.  ex:: you wear a watch (if not, you should) => don't need time & date displayed, and have timer's at hand.
  - you always know what window you are looking at by its contents.
  - you don't need visual indication of how to navigate to tabs, nor interact with the statusbar (ex: click something) => each specific tab is always on the same keybind.
- the aestetic and efficiency of a decluttered and maximized screen is (imo) unmatched.
- the theory is to make switching so ergonomic and instantaneous, engrained into muscle memory, that you are faster that people using, say 2 monitors.
- (modelines are useful (browser / emacs) as they indicate in which mode/context we are in.)

- modline only shown when explicitly toggled and used as a leadermode indicator.
#+begin_src conf
bar {
	mode hide
	workspace_buttons yes
	binding_mode_indicator yes
	modifier none
	tray_output primary
	status_command i3status
	separator_symbol " | "
	workspace_min_width 40

	colors {
		background $MODELINE_BG
		statusline $FG
		separator $FG
		#class             $border      $bg          $fg
		binding_mode       $MODELINE_BG $MODELINE_BG $MODELINE_BG
		focused_workspace  $BORDER      $ACTIVE_BG   $FG
		active_workspace   $BORDER      $MODELINE_BG $FG
		inactive_workspace $BORDER      $MODELINE_BG $FG
		urgent_workspace   $BORDER      $URGENT_BG   $FG
	}
}
#+end_src
